version: "3.8"

services:
  web:
    depends_on:
      - api
    build: ./chat-client
    ports:
      - 5173:5173
    environment:
      VITE_SOCKET_LINK: http://localhost:3001

  api:
    depends_on:
      - db
    build: ./chat-server
    ports:
      - 3001:3001
    environment:
      TOKEN_SECRET: secretTokenUwUKey
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'

volumes:
  messages:
